# Generated by Django 5.2 on 2025-08-19 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintShop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='인쇄소 ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='인쇄소 이름')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('business_hours', models.CharField(blank=True, max_length=100, verbose_name='영업시간')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('equipment_list', models.JSONField(blank=True, default=list, verbose_name='보유 장비 리스트')),
                ('available_categories', models.JSONField(blank=True, default=list, verbose_name='가능한 카테고리')),
                ('description', models.TextField(blank=True, verbose_name='인쇄소 설명')),
                ('production_time', models.CharField(blank=True, max_length=100, verbose_name='평균 제작 소요 시간')),
                ('delivery_options', models.TextField(blank=True, verbose_name='배송 옵션들')),
                ('bulk_discount', models.TextField(blank=True, verbose_name='대량 구매 할인율')),
                ('business_card_papers', models.TextField(blank=True, verbose_name='명함 용지 종류 & 설명')),
                ('business_card_quantities', models.TextField(blank=True, verbose_name='명함 수량 정보')),
                ('business_card_printing', models.TextField(blank=True, verbose_name='명함 인쇄 방식')),
                ('business_card_finishing', models.TextField(blank=True, verbose_name='명함 후가공 종류 & 설명')),
                ('banner_sizes', models.TextField(blank=True, verbose_name='배너 사이즈 종류 & 설명')),
                ('banner_stands', models.TextField(blank=True, verbose_name='배너 거치대 종류')),
                ('banner_quantities', models.TextField(blank=True, verbose_name='배너 수량 정보')),
                ('poster_papers', models.TextField(blank=True, verbose_name='포스터 용지 종류 & 설명')),
                ('poster_coating', models.TextField(blank=True, verbose_name='포스터 코팅 옵션')),
                ('poster_quantities', models.TextField(blank=True, verbose_name='포스터 수량 정보')),
                ('sticker_types', models.TextField(blank=True, verbose_name='스티커 종류 & 설명')),
                ('sticker_quantities', models.TextField(blank=True, verbose_name='스티커 수량 정보')),
                ('sticker_sizes', models.TextField(blank=True, verbose_name='스티커 사이즈 정보')),
                ('banner_large_sizes', models.TextField(blank=True, verbose_name='현수막 사이즈 정보')),
                ('banner_large_quantities', models.TextField(blank=True, verbose_name='현수막 수량 정보')),
                ('banner_large_processing', models.TextField(blank=True, verbose_name='현수막 추가가공 종류 & 설명')),
                ('brochure_papers', models.TextField(blank=True, verbose_name='브로슈어 용지 종류 & 설명')),
                ('brochure_folding', models.TextField(blank=True, verbose_name='브로슈어 형태 (접지 방식)')),
                ('brochure_sizes', models.TextField(blank=True, verbose_name='브로슈어 사이즈 정보')),
                ('brochure_quantities', models.TextField(blank=True, verbose_name='브로슈어 수량 정보')),
                ('business_license', models.FileField(blank=True, upload_to='business_licenses/', verbose_name='사업자등록증')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='수정 비밀번호')),
                ('temp_step1_data', models.JSONField(blank=True, default=dict, verbose_name='1단계 임시 데이터')),
                ('temp_step2_data', models.JSONField(blank=True, default=dict, verbose_name='2단계 임시 데이터')),
                ('registration_status', models.CharField(choices=[('step1', '1단계: 기본 정보'), ('step2', '2단계: 상세 정보'), ('completed', '등록 완료')], default='step1', max_length=20, verbose_name='등록 단계')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증 완료')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '인쇄소',
                'verbose_name_plural': '인쇄소들',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='세션 ID')),
                ('history', models.JSONField(default=list, verbose_name='대화 기록')),
                ('slots', models.JSONField(default=dict, verbose_name='슬롯 데이터')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시작일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 활동')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '채팅 세션',
                'verbose_name_plural': '채팅 세션',
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
