# Generated by Django 5.2.5 on 2025-08-18 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='세션 ID')),
                ('history', models.JSONField(default=list, verbose_name='대화 기록')),
                ('slots', models.JSONField(default=dict, verbose_name='슬롯 데이터')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시작일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 활동')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '채팅 세션',
                'verbose_name_plural': '채팅 세션',
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
