# Generated by Django 5.2.5 on 2025-08-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finishingoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='finishingoption',
            name='print_shop',
        ),
        migrations.AlterUniqueTogether(
            name='papertype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='papertype',
            name='print_shop',
        ),
        migrations.AlterUniqueTogether(
            name='printshape',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='printshape',
            name='print_shop',
        ),
        migrations.AlterUniqueTogether(
            name='printsize',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='printsize',
            name='print_shop',
        ),
        migrations.AlterUniqueTogether(
            name='quantitydiscount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quantitydiscount',
            name='print_shop',
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_info',
            field=models.TextField(blank=True, help_text='사이즈 종류, 거치대 옵션, 가격 등', verbose_name='배너 상세정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_large_info',
            field=models.TextField(blank=True, help_text='사이즈 옵션, 추가가공, 가격 등', verbose_name='현수막 상세정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='brochure_info',
            field=models.TextField(blank=True, help_text='용지 종류, 접지 방식, 사이즈, 가격 등', verbose_name='브로슈어 상세정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='business_card_info',
            field=models.TextField(blank=True, help_text='용지 종류, 후가공 옵션, 가격, 수량 할인 등', verbose_name='명함 상세정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='poster_info',
            field=models.TextField(blank=True, help_text='용지 종류, 코팅 옵션, 가격 등', verbose_name='포스터 상세정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='sticker_info',
            field=models.TextField(blank=True, help_text='스티커 종류, 용지 옵션, 가격 등', verbose_name='스티커 상세정보'),
        ),
        migrations.DeleteModel(
            name='CategoryDetail',
        ),
        migrations.DeleteModel(
            name='FinishingOption',
        ),
        migrations.DeleteModel(
            name='PaperType',
        ),
        migrations.DeleteModel(
            name='PrintShape',
        ),
        migrations.DeleteModel(
            name='PrintSize',
        ),
        migrations.DeleteModel(
            name='QuantityDiscount',
        ),
    ]
