# Generated by Django 5.2.5 on 2025-08-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printshop',
            name='business_card_sizes',
            field=models.TextField(blank=True, verbose_name='명함 사이즈 종류 & 설명'),
        ),
    ]
