# Generated by Django 5.2.5 on 2025-08-19 01:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_alter_finishingoption_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printshop',
            options={'verbose_name': '인쇄소', 'verbose_name_plural': '인쇄소들'},
        ),
        migrations.AddField(
            model_name='printshop',
            name='bulk_discount',
            field=models.JSONField(blank=True, default=dict, verbose_name='대량 구매 할인율'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='delivery_options',
            field=models.JSONField(blank=True, default=list, verbose_name='배송 옵션들'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='production_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='평균 제작 소요 시간'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='registration_status',
            field=models.CharField(choices=[('step1', '1단계: 기본 정보'), ('step2', '2단계: 상세 정보'), ('completed', '등록 완료')], default='step1', max_length=20, verbose_name='등록 단계'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='temp_step1_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='1단계 임시 데이터'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='temp_step2_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='2단계 임시 데이터'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='address',
            field=models.TextField(blank=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='available_categories',
            field=models.JSONField(blank=True, default=list, verbose_name='가능한 카테고리'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='banner_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='배너 상세 정보'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='banner_large_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='현수막 상세 정보'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='brochure_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='브로슈어 상세 정보'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='business_card_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='명함 상세 정보'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='business_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='영업시간'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='business_license',
            field=models.FileField(blank=True, upload_to='business_licenses/', verbose_name='사업자등록증'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='equipment_list',
            field=models.JSONField(blank=True, default=list, verbose_name='보유 장비 리스트'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='인쇄소 ID'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='활성화'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='인쇄소 이름'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='수정 비밀번호'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='poster_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='포스터 상세 정보'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='sticker_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='스티커 상세 정보'),
        ),
        migrations.AlterModelTable(
            name='printshop',
            table=None,
        ),
    ]
