# Generated by Django 5.2.5 on 2025-08-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_printshop_business_card_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printshop',
            name='banner_large_processing',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='banner_large_quantities',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='banner_large_sizes',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='banner_quantities',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='banner_sizes',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='banner_stands',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='brochure_folding',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='brochure_papers',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='brochure_quantities',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='brochure_sizes',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='business_card_finishing',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='business_card_papers',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='business_card_printing',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='business_card_quantities',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='business_card_sizes',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='poster_coating',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='poster_papers',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='poster_quantities',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='sticker_quantities',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='sticker_sizes',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='sticker_types',
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_large_min_quantity',
            field=models.CharField(blank=True, max_length=50, verbose_name='현수막 최소 주문 수량'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_large_processing_options',
            field=models.TextField(blank=True, verbose_name='현수막 추가가공 종류 (옵션명+가격+설명)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_large_size_options',
            field=models.TextField(blank=True, verbose_name='현수막 사이즈 종류 (사이즈명+가격+크기)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_min_quantity',
            field=models.CharField(blank=True, max_length=50, verbose_name='배너 최소 주문 수량'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_size_options',
            field=models.TextField(blank=True, verbose_name='배너 사이즈 종류 (사이즈명+가격+크기)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_stand_options',
            field=models.TextField(blank=True, verbose_name='배너 거치대 종류 (거치대명+가격+설명)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='brochure_folding_options',
            field=models.TextField(blank=True, verbose_name='브로슈어 접지 종류 (옵션명+가격+설명)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='brochure_min_quantity',
            field=models.CharField(blank=True, max_length=50, verbose_name='브로슈어 최소 주문 수량'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='brochure_paper_options',
            field=models.TextField(blank=True, verbose_name='브로슈어 용지 종류 (옵션명+가격+설명)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='brochure_size_options',
            field=models.TextField(blank=True, verbose_name='브로슈어 사이즈 종류 (사이즈명+가격+크기)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='business_card_finishing_options',
            field=models.TextField(blank=True, verbose_name='명함 후가공 옵션 (옵션명+가격+설명)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='business_card_min_quantity',
            field=models.CharField(blank=True, max_length=50, verbose_name='명함 최소 주문 수량'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='business_card_paper_options',
            field=models.TextField(blank=True, verbose_name='명함 용지 종류 (옵션명+가격+설명)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='business_card_printing_options',
            field=models.TextField(blank=True, verbose_name='명함 인쇄 방식 (옵션명+가격+설명)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='poster_coating_options',
            field=models.TextField(blank=True, verbose_name='포스터 코팅 종류 (옵션명+가격+설명)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='poster_min_quantity',
            field=models.CharField(blank=True, max_length=50, verbose_name='포스터 최소 주문 수량'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='poster_paper_options',
            field=models.TextField(blank=True, verbose_name='포스터 용지 종류 (옵션명+가격+설명)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='sticker_min_quantity',
            field=models.CharField(blank=True, max_length=50, verbose_name='스티커 최소 주문 수량'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='sticker_size_options',
            field=models.TextField(blank=True, verbose_name='스티커 사이즈 종류 (사이즈명+가격+크기)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='sticker_type_options',
            field=models.TextField(blank=True, verbose_name='스티커 종류 (옵션명+가격+설명)'),
        ),
    ]
