# Generated by Django 5.2.5 on 2025-08-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0003_alter_printshop_options_printshop_bulk_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printshop',
            name='banner_info',
            field=models.TextField(blank=True, verbose_name='배너 상세 정보 (AI 파싱용)'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='banner_large_info',
            field=models.TextField(blank=True, verbose_name='현수막 상세 정보 (AI 파싱용)'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='brochure_info',
            field=models.TextField(blank=True, verbose_name='브로슈어 상세 정보 (AI 파싱용)'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='bulk_discount',
            field=models.TextField(blank=True, verbose_name='대량 구매 할인율 (AI 파싱용)'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='business_card_info',
            field=models.TextField(blank=True, verbose_name='명함 상세 정보 (AI 파싱용)'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='delivery_options',
            field=models.TextField(blank=True, verbose_name='배송 옵션들 (AI 파싱용)'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='poster_info',
            field=models.TextField(blank=True, verbose_name='포스터 상세 정보 (AI 파싱용)'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='sticker_info',
            field=models.TextField(blank=True, verbose_name='스티커 상세 정보 (AI 파싱용)'),
        ),
    ]
