# Generated by Django 5.2.5 on 2025-08-22 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0003_remove_printshop_banner_large_processing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printshop',
            name='equipment_list',
        ),
    ]
