# Generated by Django 5.2.5 on 2025-08-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0004_alter_printshop_banner_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printshop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='인쇄소 ID'),
        ),
    ]
