# Generated by Django 5.2.5 on 2025-08-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0004_remove_printshop_equipment_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printshop',
            name='banner_large_min_quantity',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='banner_min_quantity',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='brochure_min_quantity',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='business_card_min_quantity',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='poster_min_quantity',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='sticker_min_quantity',
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_large_quantity_price_info',
            field=models.TextField(blank=True, verbose_name='현수막 수량 및 가격정보 (수량별 가격+최소주문수량)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_quantity_price_info',
            field=models.TextField(blank=True, verbose_name='배너 수량 및 가격정보 (수량별 가격+최소주문수량)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='brochure_quantity_price_info',
            field=models.TextField(blank=True, verbose_name='브로슈어 수량 및 가격정보 (수량별 가격+최소주문수량)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='business_card_quantity_price_info',
            field=models.TextField(blank=True, verbose_name='명함 수량 및 가격정보 (수량별 가격+최소주문수량)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='poster_quantity_price_info',
            field=models.TextField(blank=True, verbose_name='포스터 수량 및 가격정보 (수량별 가격+최소주문수량)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='sticker_quantity_price_info',
            field=models.TextField(blank=True, verbose_name='스티커 수량 및 가격정보 (수량별 가격+최소주문수량)'),
        ),
    ]
