# Generated by Django 5.2.5 on 2025-08-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0005_alter_printshop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printshop',
            name='banner_info',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='banner_large_info',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='brochure_info',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='business_card_info',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='poster_info',
        ),
        migrations.RemoveField(
            model_name='printshop',
            name='sticker_info',
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_large_processing',
            field=models.TextField(blank=True, verbose_name='현수막 추가가공 종류 & 설명'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_large_quantities',
            field=models.TextField(blank=True, verbose_name='현수막 수량 정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_large_sizes',
            field=models.TextField(blank=True, verbose_name='현수막 사이즈 정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_quantities',
            field=models.TextField(blank=True, verbose_name='배너 수량 정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_sizes',
            field=models.TextField(blank=True, verbose_name='배너 사이즈 종류 & 설명'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='banner_stands',
            field=models.TextField(blank=True, verbose_name='배너 거치대 종류'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='brochure_folding',
            field=models.TextField(blank=True, verbose_name='브로슈어 형태 (접지 방식)'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='brochure_papers',
            field=models.TextField(blank=True, verbose_name='브로슈어 용지 종류 & 설명'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='brochure_quantities',
            field=models.TextField(blank=True, verbose_name='브로슈어 수량 정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='brochure_sizes',
            field=models.TextField(blank=True, verbose_name='브로슈어 사이즈 정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='business_card_finishing',
            field=models.TextField(blank=True, verbose_name='명함 후가공 종류 & 설명'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='business_card_papers',
            field=models.TextField(blank=True, verbose_name='명함 용지 종류 & 설명'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='business_card_printing',
            field=models.TextField(blank=True, verbose_name='명함 인쇄 방식'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='business_card_quantities',
            field=models.TextField(blank=True, verbose_name='명함 수량 정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='poster_coating',
            field=models.TextField(blank=True, verbose_name='포스터 코팅 옵션'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='poster_papers',
            field=models.TextField(blank=True, verbose_name='포스터 용지 종류 & 설명'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='poster_quantities',
            field=models.TextField(blank=True, verbose_name='포스터 수량 정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='sticker_quantities',
            field=models.TextField(blank=True, verbose_name='스티커 수량 정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='sticker_sizes',
            field=models.TextField(blank=True, verbose_name='스티커 사이즈 정보'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='sticker_types',
            field=models.TextField(blank=True, verbose_name='스티커 종류 & 설명'),
        ),
    ]
