# Generated by Django 5.2.5 on 2025-08-22 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0005_remove_printshop_banner_large_min_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='printshop',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='관리자 메모'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='심의일'),
        ),
        migrations.AddField(
            model_name='printshop',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='심의자'),
        ),
        migrations.AlterField(
            model_name='printshop',
            name='registration_status',
            field=models.CharField(choices=[('step1', '1단계: 기본 정보'), ('step2', '2단계: 상세 정보'), ('pending', '심의 대기'), ('completed', '등록 완료'), ('rejected', '등록 거부')], default='step1', max_length=20, verbose_name='등록 단계'),
        ),
    ]
